### ISSUE TITLE
Tic-Tac-Toe in kotlin-wrappers example can't run perfectly.

### ISSUE THREAD

**Issue by leerenbo** [JetBrains/kotlin-wrappers#2396] opened 2024-08-15 06:57 UTC
Two file in Tic-Tac-Toe example:
https://github.com/JetBrains/kotlin-wrappers/blob/master/examples/old/src/jsMain/kotlin/example/TicTacToe.kt
https://github.com/JetBrains/kotlin-wrappers/blob/master/examples/old/src/jsMain/kotlin/example/TicTacToe.css

This part tell how to import .css . However, the `require` method is lacking and thus it can't be compiled.
https://github.com/JetBrains/kotlin-wrappers/blob/227c1da77a6c78d70c880837caffa3eb1b4560ba/examples/old/src/jsMain/kotlin/example/TicTacToe.kt#L120-L124

How to fix it . How to import css in kotlin?

**Comment by turansky** [comment] 2024-08-15 07:04
@leerenbo Please don't duplicate issues. If you have some questions you can write even in closed issues.

Closed as duplicate of #2393

**Closed by turansky** 2024-08-15 07:04 UTC

**Comment by leerenbo** [comment] 2024-08-15 07:19
Sorry, the previous issue wasn't described clearly enough. You closed the previous one, so I'm sending another one. 

I just tried using KotlinJS and found that the learning materials are not very comprehensive. I am learning through examples. Let's figure out how to fix and run this example properly.

**Comment by turansky** [comment] 2024-08-15 11:55
1. We don't have example of CSS import - it's expected for now
2. Example, which you request need some project changes, which we plan to do in future (not now)
3. If you need help with CSS import right now - Slack channel is best place where you can find it.
4. This question isn't related to Kotlin Wrappers directly
    * `js.import.import` function can help

**Comment by turansky** [comment] 2024-09-22 22:49
@leerenbo I started examples spliting.
Infrastructure is ready.
Tic-Tac-Toe example can be moved in separate subproject - PR is welcome. :)

**Comment by leerenbo** [comment] 2024-09-26 16:54
I can contribute a react-router-dom sample.

[https://reactrouter.com/en/main/start/tutorial](https://reactrouter.com/en/main/start/tutorial)
Rewrote the .jsx in the tutorial with KotlinJS.

This one is better written and has reference value.

**Comment by turansky** [comment] 2024-09-26 17:02
Issue, which you reported is about Tic-Tac-Toe example as I remember ;)
