### ISSUE TITLE
kotlin-react-router  wrapper  `external fun useLoaderData(): Any?`    Can the return value type of Any be changed to a generic type?

### ISSUE THREAD

**Issue by leerenbo** [JetBrains/kotlin-wrappers#2451] opened 2024-09-01 11:41 UTC
**Is your feature request related to a problem? Please describe.**
```kotlin

val ContactFC = FC {

    val contact: Contact = useLoaderData().asDynamic()

...
}
```

This is more concise.

```kotlin
val contact = useLoaderData<Contact>()
```

**Comment by turansky** [comment] 2024-09-01 12:12
Duplicate of #2452

**Closed by turansky** 2024-09-01 12:12 UTC
