### ISSUE TITLE
ring-ui webpack css error

### ISSUE THREAD

**Issue by saied89** [JetBrains/kotlin-wrappers#654] opened 2021-08-23 08:43 UTC
I'm trying to use ring-ui header (I have of course added the config block to a js file in the webpack.config.d folder)
First I encountered an error complaining that core-js can't be found. 
I added the dependency through gradle 

`implementation(npm("core-js", "3.16.2"))`

Now I'm seeing the error below. I searched a bit and found this [question](https://stackoverflow.com/questions/50261548/webpack-fails-module-build-failed-unknown-word-with-webpack-config-js-file) but don't know how to fix it.

```Compiled with problems:X

Error:

Module build failed (from ../../node_modules/css-loader/dist/cjs.js):
CssSyntaxError

(2:7) /.../build/js/node_modules/@jetbrains/ring-ui/components/alert/alert.css Unknown word

  1 | 
&gt; 2 |       var API = require(&quot;!../../node_modules/style-loader/dist/runtime/injectStylesIntoStyleTag.js&quot;);
    |       ^
  3 |       var domAPI = require(&quot;!../../node_modules/style-loader/dist/runtime/styleDomAPI.js&quot;);
  4 |       var insertFn = require(&quot;!../../node_modules/style-loader/dist/runtime/insertBySelector.js&quot;);



Error:

Module build failed (from ../../node_modules/css-loader/dist/cjs.js):
CssSyntaxError

(2:7) /.../build/js/node_modules/@jetbrains/ring-ui/components/alert/container.css Unknown word

  1 | 
&gt; 2 |       var API = require(&quot;!../../node_modules/style-loader/dist/runtime/injectStylesIntoStyleTag.js&quot;);
    |       ^
  3 |       var domAPI = require(&quot;!../../node_modules/style-loader/dist/runtime/styleDomAPI.js&quot;);
  4 |       var insertFn = require(&quot;!../../node_modules/style-loader/dist/runtime/insertBySelector.js&quot;);



Error:

Module build failed (from ../../node_modules/css-loader/dist/cjs.js):
CssSyntaxError

(2:7) /.../build/js/node_modules/@jetbrains/ring-ui/components/auth/down-notification.css Unknown word

  1 | 
&gt; 2 |       var API = require(&quot;!../../node_modules/style-loader/dist/runtime/injectStylesIntoStyleTag.js&quot;);
    |       ^
  3 |       var domAPI = require(&quot;!../../node_modules/style-loader/dist/runtime/styleDomAPI.js&quot;);
  4 |       var insertFn = require(&quot;!../../node_modules/style-loader/dist/runtime/insertBySelector.js&quot;);
  ```
  
  
p.s I have applied the WA for this [issue](https://youtrack.jetbrains.com/issue/KT-48273) so maybe a webpack 4.0.0 compatiblity issue?

```
afterEvaluate {
    rootProject.extensions.configure<org.jetbrains.kotlin.gradle.targets.js.nodejs.NodeJsRootExtension> {
        versions.webpackDevServer.version = "4.0.0"
    }
}
```

**Comment by Neitex** [comment] 2021-08-24 02:02
I've had this problem in past.
For me, disabling cssSupport at build.gradle.kts helped:
```kotlin
browser {
            ...
            commonWebpackConfig {
                cssSupport.enabled = false
            }
            ...
        }
```
I don't fully understand why, but it works :)

**Comment by turansky** [comment] 2021-08-24 02:52
AFAIK - css support disabling - requirement

cc @altavir

**Comment by altavir** [comment] 2021-08-24 07:21
The problem is that RingUI uses custom CSS loading rule with a narrow scope. Css support in gradle enables unscoped rule for css and overrides the rule from RingUI. So the only way to turn it off and to introduce those rules manually. It could be fixed with https://youtrack.jetbrains.com/issue/KT-47343.

**Closed** 2021-09-16 07:06 UTC
