### ISSUE TITLE
CSS hover selectors.. How do we use them?

### ISSUE THREAD

**Issue by Hamzantal** [JetBrains/kotlin-wrappers#83] opened 2018-09-12 13:50 UTC
Hi there JetBrains developers. Recently I was trying to build an application using 100% Kotlin. I came across an issue, where hover selectors are confusing and unintuitive, and I might be misusing them altogether. For someone to create the code for the hover of an element, intuitively, someone would want to do this:
```css
p {
  hover { color = Color.yellow }
  color = Color.blue
}
```

However, confusingly, this creates this:
```css
p {
color: blue;
&:hover {
color: yellow;
}
}
```
Please help me out in understanding how I can use the hover selector with my code effectively! Thank you very much

**Comment by Leonya** [comment] 2018-09-12 13:59
A duplicate of #77

**Closed by Leonya** 2018-09-12 13:59 UTC

**Comment by Hypnosphi** [comment] 2018-09-12 23:12
https://github.com/JetBrains/kotlin-wrappers/issues/77#issuecomment-420827396
