### ISSUE TITLE
More examples

### ISSUE THREAD

**Issue by bbodi** [JetBrains/kotlin-wrappers#13] opened 2017-11-14 20:14 UTC
Can you provide please more examples.
E.g.
- In the kotlin-fullstack-example there is an ``open class ReactExternalComponentSpec<P : RProps>(val ref: dynamic)`` class for imporing React components from external modules.
How can I achieve the same with kotlin-react?

- How can I add children components to a component using DSL, like
```kotlin
fun RBuilder.app {
    welcome("Jane") {
        div()
     }
}
```

- An example about a stateful component.

Thanks!

**Comment by Hypnosphi** [comment] 2017-11-15 00:28
> In the kotlin-fullstack-example there is an `open class ReactExternalComponentSpec<P : RProps>(val ref: dynamic)`

kotlin-fullstack-example uses their own fork of what kotlin-wrappers were before they actually were a thing =)

Now you can do this:
```
// it assumes that `const ReactSomething = require('react-something')` works in JS
@JsModule("react-something")
external val ReactSomething: RClass<dynamic>

// then somewhere inside your components
ReactSomething {
  attrs {
    foo = "bar"
  }
  // will be passed as children
  +"Hello"
}
```

Then, to add some typesafety, you can replace `dynamic` with something like this
```
external interface ReactSomethingProps: RProps {
  var foo: String
}

@JsModule("react-something")
external val ReactSomething: RClass<ReactSomethingProps>
```

> How can I add children components to a component using DSL, like
>```
>fun RBuilder.app {
>    welcome("Jane") {
>        div()
>     }
>}
>```

This is exactly the way to add child components by now (we can change it to `+div()` in future releases though)

> An example about a stateful component.

You can find one in CRKA templates: https://github.com/JetBrains/create-react-kotlin-app/blob/master/packages/react-scripts/template/src/ticker/Ticker.kt

I agree that we should add such examples to `kotlin-react` readme. @Leonya, @prigara, can someone of you handle it?

**Comment by bbodi** [comment] 2017-11-15 06:40
Thanks a lot that was really useful!

> How can I add children components to a component using DSL, like

In the provided example on the frontpage, the welcome function accepts only one parameter, so I can't provide a function as a second one (the body where in my example the div were added).

Of course I can expand my function to accept an ``childrenBuilder: RBuilder.()->Unit``, but my question is that what should happen with this ``childrenBuilder`` in the definition of the ``welcome`` function? Should I apply it on ``this`` like here?
```kotlin
fun RBuilder.welcome(childrenBuilder: RBuilder.()->Unit) = child(WelcomeComponent::class) {
    this.childrenBuilder()
}
```

**Comment by Hypnosphi** [comment] 2017-11-15 07:39
>```
>fun RBuilder.welcome(childrenBuilder: RBuilder.()->Unit) = >child(WelcomeComponent::class) {
>    this.childrenBuilder()
>}
>```

This code assumes that you have WelcomeComponent class component declared. You can actually omit `this` keyword here, which is often the case in Kotlin and Java:

```
fun RBuilder.welcome(childrenBuilder: RBuilder.()->Unit) = child(WelcomeComponent::class) {
    childrenBuilder()
}
```

Actually, you can pass not only children, but also props in that handler. So let's change its name to something more generic, and the type to `RHandler<WelcomeProps>. This 
is an alias for `RElementBuilder<WelcomeProps>.() -> Unit`, where `RElementBuilder<P>` is basically `RBuilder` with an additional ability of passing props of type `P` with `attrs.foo = "bar` or `attrs { foo = "bar" }`

```
fun RBuilder.welcome(handler: RHandler<WelcomeProps>) = child(WelcomeComponent::class) {
    handler()
}
```

In fact, it can be simplified to just
```
fun RBuilder.welcome(handler: RHandler<WelcomeProps>) = child(WelcomeComponent::class, handler)
```

There's still a question how to consume the children in your class component. Of course, you can read it from `props.children`, but it doesn't have a fixed type, so it's better to use `children()` helper:

```
class Welcome: RComponent<WelcomeProps, RState>() {
    override fun RBuilder.render() {
        div {
            +"Hello, ${props.name}"
            children()
        }
    }
}
```

If you don't use a class component, you can do this:
```
fun RBuilder.welcome(name: String, children: RBuilder.() -> Unit) {
    div {
        +"Hello, $name"
        children()
    }
}
```

**Comment by ScottHuangZL** [comment] 2017-11-20 09:15
Echo for add more examples, such as to cover the **reactjs tutorial**:)   Thanks.
At least to cover the todo sample:)

**Comment by ScottHuangZL** [comment] 2017-11-20 15:06
**Below is a simple Todo list sample:**

`
import kotlinx.html.*
import kotlinx.html.js.*
import org.w3c.dom.HTMLInputElement
import react.*
import react.dom.*

interface TodoProps : RProps {
    var items: MutableList<String?>
}

interface TodoState : RState {
    var items: MutableList<String?>
    var text: String
}

class Todo(props: TodoProps) : RComponent<TodoProps, TodoState>(props) {
    override fun TodoState.init(props: TodoProps) {
        items = props.items
        text = ""

    }

    override fun RBuilder.render() {
        div {

            input(type = InputType.text, name = "itemText") {
                key = "itemText"


                attrs {
                    value = state.text
                    placeholder = "Input todo text here..."
                    onChangeFunction = {
                        val target = it.target as HTMLInputElement
                        setState {
                            text = target.value
                        }
//                        console.log(target)
                    }
                }
            }

            button{
                +"Add"
                attrs{
                    onClickFunction = {
                        if(state.text.isNotEmpty()){
                            setState{
                                items.add(text)
                                text = ""  //clear the input text after add to list
                            }
                        }
                    }
                }
            }


//            +state.text



            h3 {
                ul {
                    for ((index, item) in state.items.withIndex()) {
                        li {
                            key = index.toString()
                            +item.toString()
                            button {
                                +"X"
                                attrs {
                                    onClickFunction = {
//                                        console.log(index, item)
                                        setState {
                                            items.removeAt(index)
                                        }
//                                        console.log(state.items)
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }

}

fun RBuilder.todo(items: MutableList<String?> = mutableListOf("Hello", "World")) = child(Todo::class) {
    attrs.items = items
}`

**Comment by Hypnosphi** [comment] 2017-11-20 15:35
@ScottHuangZL  I've edited your message to point to your PR (hope you don't mind)

**Comment by ScottHuangZL** [comment] 2017-11-20 15:40
@Hypnosphi    NP.

**Comment by ScottHuangZL** [comment] 2017-11-21 14:37
Add one sample to implement react TicTacToe tutorial.  Store the state in board level only in this example.
https://github.com/JetBrains/kotlin-wrappers/pull/17


Will provide further example to put state at game level soon.

**Comment by ScottHuangZL** [comment] 2017-11-22 08:52
Complete the full function TicTacToe tutorial sample.  Hope @Hypnosphi  or @Leonya  accept the pull request :) thanks.

Suggest both keep that 2 versions, 1st one for basic, and 2nd version for basic plus.  

https://github.com/JetBrains/kotlin-wrappers/pull/18

**Comment by ScottHuangZL** [comment] 2017-11-23 15:07
https://github.com/ScottHuangZL/my-kotlin-app

**Comment by ScottHuangZL** [comment] 2017-11-24 10:10
https://github.com/JetBrains/kotlin-wrappers/pull/21

This is a port of https://reactjs.org/docs/thinking-in-react.html

**Comment by bbodi** [comment] 2017-11-26 12:34
Hi,

I would like to ask about React Stateless Components, e.g.:
```jsx
const Username = function(props) {
  return (
    <p>The logged in user is: {props.username}</p>
  )
}
```
I could produce something similar with kotlin-wrappers:
```kotlin
override fun getComponentForKey(key: String): (props: dynamic) -> dynamic {
        return { props ->
            buildElements({
                span {
                    childList.addAll(React.Children.toArray(props.children)) // ??
                }
            })
        }
    }
```
This method implements an interface from DraftJs, and has to return a React component.

My first question: is this implementation(using the buildElements) the right way to do this?
Second, I couldn't use the ``children()`` method in my method at the line with comments ``??``, because ``children`` is defined inside ``ReactComponent`` as an extension function for ``RBuilder``. So had to copy its implementation into that line.
Which makes me think that either my implementation is wrong, or maybe the ``children()`` method should put into ``RBuilder``.

**Comment by Hypnosphi** [comment] 2017-11-26 13:44
Yes, if some external library expects actual react elements, using `buildElements` is the correct approach.
As for `children` function, I think we could add the corresponding helper on `RBuilder`, but you’d need to pass `props.children` to it:
```
children(props.children)
```

**Comment by Hypnosphi** [comment] 2017-11-27 23:44
@bbodi Actually, I found a way to make it work like that:
```
override fun getComponentForKey(key: String): (props: RProps) -> dynamic {
    return { props ->
        buildElements {
            span {
                props.children()
            }
        }
    }
}
```

It works since `@jetbrains/kotlin-react@16.0.0-pre.12` (included in `react-scripts-kotlin@2.1.0`)

**Comment by ScottHuangZL** [comment] 2017-11-29 14:55
@Hypnosphi   I try to import an example from https://www.npmjs.com/package/react-quill
It should be show how to leverage existing external react component

Main code as below. And I try call it in app.kt as  **`quill("<p>A quill edit <b>example</b></>")`**
**It can normally show the given value in the quill editor, sound the import example is ok.**
 
However, when I try change the content in the editor, it show error in the console as: 
**The given range isn't in document.**

Is it caused by the onChange need bind to this?
Or I need change onChange typing as below? It seems similar error result
   var onChange: (String) -> Unit

**Can you shed a light for how to resolve the issue.**

===main code as below ======
```
@JsModule("react-quill")
external val reactQuill: RClass<ReactQuillProps>

external interface ReactQuillProps : RProps {
    var value: String
    var onChange: (Event) -> Unit
}

interface QuillProps : RProps {
    var initialText: String
}

interface QuillState : RState {
    var text: String
}


class Quill(props: QuillProps) : RComponent<QuillProps, QuillState>(props) {
    override fun QuillState.init(props: QuillProps) {
        text = props.initialText
    }

    private fun handleChange(value: String) {
        setState {
            text = value
        }
        console.log(value)
    }

    override fun RBuilder.render() {
        div {
            reactQuill {
                attrs {
                    value = state.text
                    onChange = { handleChange(value) }
                }
            }
        }
    }
}

fun RBuilder.quill(quillValue: String) = child(Quill::class) {
    attrs.initialText = quillValue
}

```

**Comment by Hypnosphi** [comment] 2017-11-29 15:09
> `onChange = { handleChange(value) }`

It should be `{ value -> handleChange(value) }` (or just `{ handleChange(it) }`). You can also try `onChange = ::handleChange`

**Comment by ScottHuangZL** [comment] 2017-11-30 01:36
It works! Thanks @Hypnosphi  for your always help.
... 
var onChange: (String) -> Unit
...
reactQuill {
                attrs {
                    value = state.text
                    onChange = { handleChange(it) }
                }
            }

**Comment by ScottHuangZL** [comment] 2017-12-03 05:07
@Hypnosphi   Can you add some articles/blogs to deep dive the kotlin-wrapper & kotlin-react?  And then you can close this issue accordingly? Thanks.

**Comment by Hypnosphi** [comment] 2017-12-03 10:36
@prigara do we have any?

**Comment by prigara** [comment] 2017-12-04 12:28
@Hypnosphi, @ScottHuangZL unfortunately, we don't have any articles or tutorials yet. Maybe we should add a link to the [Koltin JavaScript docs](https://kotlinlang.org/docs/reference/dynamic-type.html)?

**Comment by deviant-studio** [comment] 2018-02-18 15:41
guys, how ca i run examples from the examples folder? what gradle command should i use to start the frontend?

**Comment by Hypnosphi** [comment] 2018-02-18 16:02
There are currently no setup tu run the examples, you can only build them

**Comment by Hypnosphi** [comment] 2018-02-25 12:46
Right now, this should work:

```
attrs.asDynamic().foo = "bar"
```

We can find a better way to do that though. Basically, what's needed is to add an extension function `operator fun RProps.set()`

**Comment by deviant-studio** [comment] 2018-02-25 13:08
thanks. this one did the trick:
```kotlin
operator fun RProps.set(key: String, value: dynamic) {
    asDynamic()[key] = value
}
```

**Comment by ScottHuangZL** [comment] 2018-02-28 08:35
@deviant-studio  you can try the example from https://github.com/ScottHuangZL/my-kotlin-app
I believe you have clone and successful run in your local computer.
btw, please "npm install" to get necessary lib in advance after clone. Thanks.

**Comment by ManifoldFR** [comment] 2018-04-08 09:48
I've been trying to create headers for the [`react-google-maps`](https://tomchentw.github.io/react-google-maps/#withgooglemap) library, which uses a set of higher order components `withGoogleMap` and `withScriptjs` to wrap a `GoogleMap` component.

I write the header for `GoogleMap` as follows
```kotlin
/**
 * Headers for the react-google-maps JS library
 */
@file:JsModule("react-google-maps")
package jsheaders

import react.*
import kotlin.js.Json

external val GoogleMap : RClass<RGMapProps>

external interface RGMapProps : RProps {

    var defaultZoom : Int
    var defaultCenter : Json
}
```
as explained in issue #13.

How do I write the header for the HOCs ? I tried
```kotlin
external fun withGoogleMap(component: ReactElement) : ReactElement
```
and defining my map component with
```kotlin
fun RBuilder.myMapComponent() {
    withGoogleMap(GoogleMap {
        attrs {
            defaultZoom = 15
            defaultCenter = json(
                    "lat" to -34.397,
                    "lng" to 150.644
            )
        }
    })
}
```

But I still get the error

    Error: Did you wrap <GoogleMap> component with withGoogleMap() HOC?

as if wrapping failed.

**Comment by ManifoldFR** [comment] 2018-04-08 13:07
Okay, I got a bit further by defining `withGoogleMap` as
```kotlin
external val withGoogleMap : (RClass<RGMapProps>) -> RClass<RGMapProps>
```
and defining my map component as
```kotlin

fun RBuilder.myMapComponent() {
    println(withGoogleMap.toString())

    withGoogleMap(GoogleMap)({
        attrs.defaultCenter = luxembourgCenter
        attrs.defaultZoom = 15
    })
}
```

Though I would've liked to understand how the HOC interface works.

**Comment by Hypnosphi** [comment] 2018-04-08 17:39
```
external val withGoogleMap : HOC<RProps, RGMapProps>
```

yes, this one should work

**Comment by ManifoldFR** [comment] 2018-04-09 10:37
How should I use it, then ? Doing 
```kotlin
withGoogleMap(GoogleMap) { }
```
does not work...

**Comment by Hypnosphi** [comment] 2018-04-09 11:31
What's the error?

**Comment by Hypnosphi** [comment] 2018-04-09 13:41
What's the type of `GoogleMap` in your case?

**Comment by ManifoldFR** [comment] 2018-04-09 13:43
```kotlin
external val GoogleMap : RClass<RGMapProps>
```
as above.

**Comment by ManifoldFR** [comment] 2018-04-09 16:12
I think it might be a problem with how I use `@file:JsModule("react-google-maps")` to import the JavaScript `react-google-maps` library. Somehow, it does not allow me to use the `withGoogleMap` HOC object I define.

**Comment by ManifoldFR** [comment] 2018-04-09 22:27
I am using Kotlin 1.2.31 and `kotlin-react:16.3.1-pre.25-kotlin-1.2.30`

**Comment by ManifoldFR** [comment] 2018-04-10 00:56
It seems importing `react.invoke` does the trick, for some reason...

**Comment by Hypnosphi** [comment] 2018-04-10 11:34
`import react.*` should work as well

**Comment by ManifoldFR** [comment] 2018-04-10 11:41
Yes it does! I'm thinking of providing my wrapper for `react-google-maps` as an example. I'll get around to making a repo for it soon enough

**Comment by ManifoldFR** [comment] 2018-04-17 09:07
Are there any examples of how to import methods defined in React components ?

**Comment by Hypnosphi** [comment] 2018-04-17 09:57
Which components expect you to do that? They really shouldn’t

**Comment by ManifoldFR** [comment] 2018-04-17 09:58
The `GoogleMap` component of `react-google-maps` has a method called `getBounds` defined. I was wondering about how to expose it to Kotlin.

**Comment by Hypnosphi** [comment] 2018-04-17 10:09
Is its usage (in JS) documented somewhere?

**Comment by ManifoldFR** [comment] 2018-04-17 10:14
Yes, here https://tomchentw.github.io/react-google-maps/#googlemap
It's not very detailed, though

**Comment by Hypnosphi** [comment] 2018-04-17 12:09
OK, you should be able to do something like this:

```
external interface GoogleMapInstance {
  fun getBounds(): Bounds
}

class MyMapComponent: RComponent<RProps, RState>() {
  var mapRef: GoogleMapInstance? = null

  fun getBounds(): Bounds? = mapRef?.getBounds()

  override fun RBuilder.render() {
     withGoogleMap(GoogleMap)({
        ref { mapRef = it }
     })
  }
}

```

**Comment by ManifoldFR** [comment] 2018-04-17 16:59
Just so I understand, what you're doing with
```kotlin
withGoogleMap(GoogleMap)({
        ref = mapRef
     })
```
is passing a lambda to the composed GoogleMap component, with RWithGoogleMap props ?

**Comment by Hypnosphi** [comment] 2018-04-17 19:50
Here I'm using new createRef feature: https://reactjs.org/blog/2018/03/29/react-v-16-3.html#createref-api

**Closed** 2021-09-17 07:34 UTC
